---
authors:
  - "René Moser (@resmo)"
  - "Yanis Guenane (@Spredzy)"
  - "jasites (@jasites)"
dependencies: {}
description: "Ansible Collection for Vultr Cloud"
documentation: "https://docs.ansible.com/ansible/latest/collections/vultr/cloud/"
homepage: "https://github.com/vultr/ansible-collection-vultr"
issues: "https://github.com/vultr/ansible-collection-vultr/issues"
license_file: COPYING
name: cloud
namespace: vultr
readme: README.md
repository: "https://github.com/vultr/ansible-collection-vultr"
tags:
  - cloud
  - vultr
version: 1.11.0
